# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-12-19 10:39
from __future__ import unicode_literals

import django.contrib.postgres.fields.hstore
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postmark', '0003_auto_20160502_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailmessage',
            name='headers_hstore',
            field=django.contrib.postgres.fields.hstore.HStoreField(default={}, verbose_name='Headers'),
            preserve_default=False,
        ),
    ]
