# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-12-19 10:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postmark', '0005_auto_20161219_1039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailmessage',
            name='headers',
        ),
    ]
