# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-12-27 16:49
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postmark', '0008_auto_20161227_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailmessage',
            name='attachments',
            field=django.contrib.postgres.fields.jsonb.JSONField(verbose_name='Attachments'),
        ),
    ]
